### ISSUE TITLE
Question about the I3D-HUMAN Dataset

### ISSUE THREAD

**Issue by yahui-lee** [Yifever20002/Dyco#1]
Hello, thank you for your great work. While using the dataset you released, I3D-HUMAN, I noticed that the images in the training set are incomplete, starting from frame 301, with one frame every 5 frames. Could you please let me know where I can access the complete data for I3D-HUMAN? Looking forward to your response.

**Comment by Yifever20002** [comment]
Thank you for your interest! We have released the full dataset, excluding some frames before frame 301, which were used for calibration. As for the frame intervals, we only processed data with appropriate intervals, so you can consider it as the raw data.

**Comment by yahui-lee** [comment]
Thank you for your response. At the moment, I have encountered another issue. I tried to understand the composition of the data, but I couldn’t find the SMPL shape parameters in any of the .pkl files. Could you let me know if these parameters are available in the data you provided?

**Comment by Yifever20002** [comment]
As we didn't use the SMPL shape parameters in our pipeline, they're not included in our dataset.

**Comment by yahui-lee** [comment]
got it. anyway, thanks for your response.

**Comment by yahui-lee** [comment]
I noticed that in your ID-novelview and ID-novelpose folders, the data is not sampled at a 5-frame interval, which is different from the training set. Could you provide the complete data with a 5-frame interval similar to the training set? Since the ID-novelview data is sampled at 30 or 50-frame intervals, it makes it difficult for me to conduct tests using other methods. Additionally, the amount of data in ID-novelview is quite limited. I would greatly appreciate it if you could provide the complete dataset. I look forward to your reply.
